import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { compile } from 'json-schema-to-typescript';
import { format, resolveConfig } from 'prettier';
import commandArgsSchema from './contracts/v1/command-args.schema.json' with { type: 'json' };
import commandValuesSchema from './contracts/v1/command-values.schema.json' with { type: 'json' };
import eventPayloadsSchema from './contracts/v1/event-payloads.schema.json' with { type: 'json' };

const root = path.resolve(import.meta.dirname, '..');
function namespacedDefinitions(
  source: { definitions: Record<string, unknown> },
  rootName: string,
  prefix: string,
) {
  const definitions = structuredClone(source.definitions);
  const names = new Map(
    Object.keys(definitions).map((name) => [name, name === rootName ? name : `${prefix}${name}`]),
  );
  const rewrite = (node: unknown) => {
    if (!node || typeof node !== 'object') return;
    if ('$ref' in node && typeof node.$ref === 'string') {
      const name = node.$ref.match(/^#\/definitions\/(.+)$/)?.[1];
      if (name && names.has(name)) node.$ref = `#/definitions/${names.get(name)}`;
    }
    for (const value of Object.values(node)) rewrite(value);
  };
  rewrite(definitions);
  return Object.fromEntries(
    Object.entries(definitions).map(([name, definition]) => [names.get(name), definition]),
  );
}

const definitions = {
  ...namespacedDefinitions(commandArgsSchema, 'CommandArgs', 'Args'),
  ...namespacedDefinitions(commandValuesSchema, 'CommandValues', 'Values'),
  ...namespacedDefinitions(eventPayloadsSchema, 'DesktopEventPayloads', 'Events'),
};

const args = commandArgsSchema.definitions.CommandArgs.properties;
const values = commandValuesSchema.definitions.CommandValues.properties;
const eventPayloads = eventPayloadsSchema.definitions.DesktopEventPayloads.properties;
assert.equal(Object.keys(args).length, 141, 'Expected 141 command argument schemas');
assert.deepEqual(Object.keys(args), Object.keys(values), 'Command argument/value schema drift');
assert.equal(Object.keys(eventPayloads).length, 17, 'Expected 17 fixed renderer event schemas');

const combinedSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'DesktopContractTypes',
  type: 'object',
  additionalProperties: false,
  properties: {
    commandArgs: { $ref: '#/definitions/CommandArgs' },
    commandValues: { $ref: '#/definitions/CommandValues' },
    eventPayloads: { $ref: '#/definitions/DesktopEventPayloads' },
  },
  required: ['commandArgs', 'commandValues', 'eventPayloads'],
  definitions,
};

const generatedSource = await compile(
  combinedSchema as Parameters<typeof compile>[0],
  'DesktopContractTypes',
  {
    bannerComment:
      '// Generated from electron/contracts/v1/*.schema.json. Do not edit this file directly.',
    style: { singleQuote: true },
    unreachableDefinitions: false,
  },
);
const generated = await format(generatedSource, {
  ...(await resolveConfig(path.join(root, 'src/lib/desktop/generated-contract-types.ts'))),
  parser: 'typescript',
});
const commandNames = Object.keys(args);
const eventNames = Object.keys(eventPayloads);
const artifacts = new Map([
  [path.join(root, 'src/lib/desktop/generated-contract-types.ts'), generated],
  [path.join(root, 'electron/commands.json'), `${JSON.stringify(commandNames, null, 2)}\n`],
  [path.join(root, 'electron/events.json'), `${JSON.stringify(eventNames, null, 2)}\n`],
  [
    path.join(root, 'src/lib/desktop/contract.ts'),
    '// Generated from electron/contracts/v1/*.schema.json. Do not edit directly.\n' +
      `export type DesktopCommand = ${commandNames.map((name) => JSON.stringify(name)).join(' | ')};\n` +
      `export type DesktopEvent = ${eventNames.map((name) => JSON.stringify(name)).join(' | ')} | \`ssh-data:\${string}\`;\n`,
  ],
]);

for (const [file, contents] of artifacts)
  if (process.argv.includes('--check'))
    assert.equal(fs.readFileSync(file, 'utf8'), contents, `${path.relative(root, file)} drift`);
  else fs.writeFileSync(file, contents);

console.log('Generated 141 command and 17 fixed event model pairs from contract schema v1');
