// Read the existing business wrappers through the TypeScript checker. No invented
// duplicate interfaces: generated types import the original model declarations.
import ts from 'typescript';
import * as fs from 'node:fs';
import * as path from 'node:path';
import assert from 'node:assert/strict';
import contracts from './contract.json' with { type: 'json' };

const __dirname = import.meta.dirname;
const root = path.resolve(__dirname, '..');
const byName = new Map(contracts.map((c) => [c.command, c]));
const config = ts.readConfigFile(path.join(root, 'tsconfig.json'), ts.sys.readFile);
const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, root);
const program = ts.createProgram(parsed.fileNames, parsed.options);
const checker = program.getTypeChecker();
const found = new Map<
  string,
  { args: string; result: string; preferred: boolean; source: string; wrapper?: string }
>();
const flags = ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.UseFullyQualifiedType;
const text = (t: ts.Type) =>
  checker
    .typeToString(t, undefined, flags)
    .replaceAll(root + '/src/', '@/')
    .replace(/`\$\{string\}-\$\{string\}-\$\{string\}-\$\{string\}-\$\{string\}`/g, 'string');
for (const source of program.getSourceFiles())
  if (source.fileName.startsWith(root + '/src/') && !source.fileName.includes('__tests__')) {
    function visit(n: ts.Node) {
      if (
        ts.isCallExpression(n) &&
        n.arguments[0] &&
        ts.isStringLiteral(n.arguments[0]) &&
        byName.has(n.arguments[0].text) &&
        /^(invoke|invokeLogged|invokeTerminalHotPath)$/.test(n.expression.getText(source))
      ) {
        const name = n.arguments[0].text;
        const c = byName.get(name)!;
        const previous = found.get(name);
        if (previous && (!source.fileName.endsWith('/lib/ipc/tauri.ts') || previous.preferred))
          return;
        const obj = n.arguments[1] ? checker.getTypeAtLocation(n.arguments[1]) : null;
        const args = c.args
          .map((a) => {
            const prop = obj?.getProperty(a.name);
            assert.ok(prop, `${name}.${a.name} not present in business wrapper`);
            const rust = a.rustType.replace(/^Option<(.*)>$/, '$1');
            let typ =
              rust === 'String'
                ? 'string'
                : rust === 'bool'
                  ? 'boolean'
                  : /^[uif]\d+$/.test(rust)
                    ? 'number'
                    : text(checker.getTypeOfSymbolAtLocation(prop, n.arguments[1]!));
            if (a.optional) typ = typ.replace(/ \| undefined/g, '') + ' | null';
            return `${a.name}${a.optional ? '?' : ''}: ${typ};`;
          })
          .join(' ');
        let fn: ts.Node | undefined = n.parent;
        while (fn && !ts.isFunctionDeclaration(fn)) fn = fn.parent;
        const annotated =
          fn && ts.isFunctionDeclaration(fn) && fn.type
            ? checker.getTypeFromTypeNode(fn.type)
            : null;
        let result = text(
          n.typeArguments?.[0]
            ? checker.getTypeFromTypeNode(n.typeArguments[0])
            : checker.getAwaitedType(annotated || checker.getTypeAtLocation(n))!,
        );
        if (c.returns === '()' || c.returns.startsWith('Result<(),')) result = 'void';
        if (c.returns.startsWith('Result<Option<'))
          result =
            result
              .replace(/ \| undefined/g, '')
              .replace(/undefined \| /g, '')
              .replace(/ \| null/g, '') + ' | null';
        if (name === 'ai_model_declaration_template') {
          /* Same AiProviderConfig as ai_resolve_model, before UI declaration transformation. */
        }
        if (c.returns === 'PetdexConnectionStatus')
          result = 'import("@/types").PetdexConnectionStatus';
        if (name === 'retrieve_key_credential')
          result = 'import("@/lib/desktop/wire-types").KeyCredentialResponse | null';
        if (name === 'list_key_credentials')
          result = 'import("@/lib/desktop/wire-types").KeyCredentialSummary[]';
        assert.ok(!['unknown', 'any'].includes(result), `${name} has no concrete model`);
        found.set(name, {
          args:
            name === 'store_key_credential'
              ? '{ request: import("@/lib/desktop/wire-types").KeyCredentialRequest; }'
              : name === 'ai_model_declaration_template'
                ? '{ provider: import("@/types/ai").AiProviderConfig; }'
                : `{ ${args} }`,
          result,
          preferred: source.fileName.endsWith('/lib/ipc/tauri.ts'),
          source: path.relative(root, source.fileName),
          wrapper: fn && ts.isFunctionDeclaration(fn) ? fn.name?.text : undefined,
        });
      }
      ts.forEachChild(n, visit);
    }
    visit(source);
  }
assert.equal(found.size, 141);
let output = '// Generated by electron/build-command-types.ts from existing business wrappers.\n';
for (const [map, field] of [
  ['CommandArgs', 'args'],
  ['CommandValues', 'result'],
] as const) {
  output += `export interface ${map} {\n`;
  for (const c of contracts) {
    const row = found.get(c.command)!;
    output += `  /** ${row.source} ${row.wrapper || ''}; ${c.source} */\n  ${c.command}: ${row[field]};\n`;
  }
  output += '}\n';
}
output +=
  'export type CommandInput<C extends keyof CommandArgs> = {} extends CommandArgs[C] ? [args?: CommandArgs[C]] : [args: CommandArgs[C]];\n';
output += 'export type WireValue<T> = [T] extends [void] ? null : T;\n';
const file = path.join(root, 'src/lib/desktop/command-types.ts');
if (process.argv.includes('--check'))
  assert.equal(fs.readFileSync(file, 'utf8'), output, 'Command types drift; regenerate and review');
else fs.writeFileSync(file, output);
console.log('Derived 141 argument/result model pairs from business wrapper declarations');
