// Generated by electron/build-command-types.ts from existing business wrappers.
export interface CommandArgs {
  /** src/lib/petdex/petdex.ts configurePetdex; native/src/petdex.rs */
  petdex_set_enabled: { enabled: boolean; };
  /** src/lib/petdex/petdex.ts getPetdexStatus; native/src/petdex.rs */
  petdex_get_status: {  };
  /** src/lib/petdex/petdex.ts testPetdexConnection; native/src/petdex.rs */
  petdex_test_connection: {  };
  /** src/lib/ipc/tauri.ts invokeGetSystemHealth; native/src/health.rs */
  get_system_health: {  };
  /** src/lib/ipc/tauri.ts invokeListAiRoutes; native/src/ai.rs */
  ai_list_routes: {  };
  /** src/lib/ipc/tauri.ts invokeSaveAiRoutes; native/src/ai.rs */
  ai_save_routes: { input: { routes: import("@/types/ai").ProviderRoute[]; defaultSelection?: import("@/types/ai").ModelSelection | undefined; expectedRevision: number; secrets?: Record<string, string> | undefined; }; };
  /** src/lib/ipc/tauri.ts invokeListAiRouteModels; native/src/ai.rs */
  ai_list_route_models: { routeId: string; };
  /** src/lib/ipc/tauri.ts invokeResolveAiSelection; native/src/ai.rs */
  ai_resolve_selection: { input: { selection: import("@/types/ai").ModelSelection; expectedRevision: number; }; };
  /** src/lib/ipc/tauri.ts invokeListAiSessionMigrations; native/src/ai.rs */
  ai_list_session_migrations: {  };
  /** src/lib/ipc/tauri.ts invokeConvertAiSessionV4; native/src/ai.rs */
  ai_convert_session_v4_to_v5: { input: { sessionId: string; }; };
  /** src/lib/ipc/tauri.ts invokeListAiModels; native/src/ai.rs */
  ai_list_models: { provider: import("@/types/ai").AiProviderConnectionConfig; };
  /** src/lib/ai/provider-contract.ts loadResolvedModel; native/src/ai.rs */
  ai_resolve_model: { provider: import("@/types/ai").AiProviderConfig; };
  /** src/components/ai/provider-setup-dialog.tsx ; native/src/ai.rs */
  ai_model_declaration_template: { provider: import("@/types/ai").AiProviderConfig; };
  /** src/lib/ipc/tauri.ts invokeCreateSession; native/src/commands.rs */
  create_session: { request: import("@/types/index").SessionCreateRequest; };
  /** src/lib/ipc/tauri.ts invokeCreateLocalSession; native/src/commands.rs */
  create_local_session: { cols: number; rows: number; };
  /** src/lib/ipc/tauri.ts invokeWriteSession; native/src/commands.rs */
  write_session: { sessionId: string; data: string; };
  /** src/lib/ipc/tauri.ts invokeGetSessionStatus; native/src/commands.rs */
  get_session_status: { sessionId: string; };
  /** src/lib/ipc/tauri.ts invokeMarkSessionReady; native/src/commands.rs */
  mark_session_ready: { sessionId: string; };
  /** src/lib/ipc/tauri.ts invokeSetSessionOutputPaused; native/src/commands.rs */
  set_session_output_paused: { sessionId: string; paused: boolean; };
  /** src/lib/ipc/tauri.ts invokeResizeSession; native/src/commands.rs */
  resize_session: { sessionId: string; cols: number; rows: number; };
  /** src/lib/ipc/tauri.ts invokeCloseSession; native/src/commands.rs */
  close_session: { sessionId: string; };
  /** src/lib/ipc/tauri.ts invokeRequestAppRestart; native/src/commands.rs */
  request_app_restart: {  };
  /** src/App.tsx ; native/src/commands.rs */
  request_app_exit: {  };
  /** src/lib/ipc/tauri.ts invokeListRemoteDirectory; native/src/commands.rs */
  list_remote_directory: { request: import("@/types/index").RemoteDirectoryRequest; };
  /** src/lib/ipc/tauri.ts invokeSupersedeRemoteDirectoryRequest; native/src/commands.rs */
  supersede_remote_directory_request: { requestKey: string; requestId: number; };
  /** src/lib/ipc/tauri.ts invokeResolveRemoteEntryOwners; native/src/commands.rs */
  resolve_remote_entry_owners: { request: import("@/types/index").RemoteEntryOwnersRequest; };
  /** src/lib/ipc/tauri.ts invokeWarmRemoteConnection; native/src/commands.rs */
  warm_remote_connection: { request: import("@/types/index").RemoteConnectionRequest; };
  /** src/lib/ipc/tauri.ts invokeCreateRemoteEntry; native/src/commands.rs */
  create_remote_entry: { request: import("@/types/index").CreateRemoteEntryRequest; };
  /** src/lib/ipc/tauri.ts invokeRenameRemotePath; native/src/commands.rs */
  rename_remote_path: { request: import("@/types/index").RenameRemotePathRequest; };
  /** src/lib/ipc/tauri.ts invokeDeleteRemotePath; native/src/commands.rs */
  delete_remote_path: { request: import("@/types/index").DeleteRemotePathRequest; };
  /** src/lib/ipc/tauri.ts invokeCopyRemotePath; native/src/commands.rs */
  copy_remote_path: { request: import("@/types/index").CopyRemotePathRequest; };
  /** src/lib/ipc/tauri.ts invokeCopyRemoteToRemote; native/src/commands.rs */
  copy_remote_to_remote: { request: import("@/types/index").CopyRemoteToRemoteRequest; };
  /** src/lib/ipc/tauri.ts invokeCancelRemoteCopy; native/src/commands.rs */
  cancel_remote_copy: { operationId: string; };
  /** src/lib/ipc/tauri.ts invokeUploadLocalPaths; native/src/commands.rs */
  upload_local_paths: { request: import("@/types/index").UploadLocalPathsRequest; };
  /** src/lib/ipc/tauri.ts invokeCopyLocalPaths; native/src/commands.rs */
  copy_local_paths: { request: import("@/types/index").CopyLocalPathsRequest; };
  /** src/lib/ipc/tauri.ts invokeRenameLocalPath; native/src/commands.rs */
  rename_local_path: { path: string; newName: string; };
  /** src/lib/ipc/tauri.ts invokePasteLocalPaths; native/src/commands.rs */
  paste_local_paths: { sourcePaths: string[]; destinationDirectory: string; copySuffix: string; };
  /** src/lib/ipc/tauri.ts invokeTrashLocalPaths; native/src/commands.rs */
  trash_local_paths: { paths: string[]; };
  /** src/lib/ipc/tauri.ts invokeCancelUpload; native/src/commands.rs */
  cancel_upload: { operationId: string; };
  /** src/lib/ipc/tauri.ts invokeCancelDelete; native/src/commands.rs */
  cancel_delete: { operationId: string; };
  /** src/lib/ipc/tauri.ts invokeDownloadRemotePaths; native/src/commands.rs */
  download_remote_paths: { request: import("@/types/index").DownloadRemotePathsRequest; };
  /** src/lib/ipc/tauri.ts invokeCancelDownload; native/src/commands.rs */
  cancel_download: { operationId: string; };
  /** src/lib/ipc/tauri.ts invokeDisconnectSftp; native/src/commands.rs */
  disconnect_sftp: { request: import("@/types/index").RemoteConnectionRequest; };
  /** src/lib/ipc/tauri.ts invokeOpenPath; native/src/commands.rs */
  open_path: { path: string; };
  /** src/lib/ipc/tauri.ts invokePickLocalFiles; native/src/commands.rs */
  pick_local_files: {  };
  /** src/lib/ipc/tauri.ts invokePickLocalFolder; native/src/commands.rs */
  pick_local_folder: { title?: string | null; };
  /** src/lib/ipc/tauri.ts invokePickPrivateKeyFile; native/src/commands.rs */
  pick_private_key_file: {  };
  /** src/lib/ipc/tauri.ts invokeOpenRemoteFile; native/src/commands.rs */
  open_remote_file: { request: import("@/types/index").OpenRemoteFileRequest; };
  /** src/lib/ipc/tauri.ts invokePreviewLocalFile; native/src/commands.rs */
  preview_local_file: { path: string; };
  /** src/lib/ipc/tauri.ts invokePreviewRemoteFile; native/src/commands.rs */
  preview_remote_file: { request: import("@/types/index").ReadRemoteFileRequest; };
  /** src/lib/ipc/tauri.ts invokeCancelRemoteFileRead; native/src/commands.rs */
  cancel_remote_file_read: { operationId: string; };
  /** src/lib/ipc/tauri.ts invokeUpdateRemotePermissions; native/src/commands.rs */
  update_remote_permissions: { request: import("@/types/index").UpdateRemotePermissionsRequest; };
  /** src/lib/ipc/tauri.ts invokeStoreKeyCredential; native/src/commands.rs */
  store_key_credential: { request: import("@/lib/desktop/wire-types").KeyCredentialRequest; };
  /** src/lib/ipc/tauri.ts invokeListKeyCredentials; native/src/commands.rs */
  list_key_credentials: {  };
  /** src/lib/ipc/tauri.ts invokeRetrieveKeyCredential; native/src/commands.rs */
  retrieve_key_credential: { id: string; };
  /** src/lib/ipc/tauri.ts invokeDeleteKeyCredential; native/src/commands.rs */
  delete_key_credential: { id: string; };
  /** src/lib/ipc/tauri.ts invokeReadTextFile; native/src/commands.rs */
  read_text_file: { path: string; };
  /** src/lib/ipc/tauri.ts invokeStoreProfilePassword; native/src/commands.rs */
  store_profile_password: { profileId: string; password: string; };
  /** src/lib/ipc/tauri.ts invokeRetrieveProfilePassword; native/src/commands.rs */
  retrieve_profile_password: { profileId: string; };
  /** src/lib/ipc/tauri.ts invokeDeleteProfilePassword; native/src/commands.rs */
  delete_profile_password: { profileId: string; };
  /** src/lib/ipc/tauri.ts invokeStoreProfileSecret; native/src/commands.rs */
  store_profile_secret: { profileId: string; kind: import("@/types/index").ProfileSecretKind; value: string; };
  /** src/lib/ipc/tauri.ts invokeRetrieveProfileSecret; native/src/commands.rs */
  retrieve_profile_secret: { profileId: string; kind: import("@/types/index").ProfileSecretKind; };
  /** src/lib/ipc/tauri.ts invokeDeleteProfileSecrets; native/src/commands.rs */
  delete_profile_secrets: { profileId: string; };
  /** src/lib/ipc/tauri.ts invokeDeleteProfileSecret; native/src/commands.rs */
  delete_profile_secret: { profileId: string; kind: import("@/types/index").ProfileSecretKind; };
  /** src/lib/ipc/tauri.ts invokeStartPortForward; native/src/commands.rs */
  start_port_forward: { request: import("@/types/index").PortForwardStartRequest; };
  /** src/lib/ipc/tauri.ts invokeStopPortForward; native/src/commands.rs */
  stop_port_forward: { operationId: string; };
  /** src/lib/ipc/tauri.ts invokeStopAllPortForwards; native/src/commands.rs */
  stop_all_port_forwards: {  };
  /** src/lib/ipc/tauri.ts invokeListPortForwards; native/src/commands.rs */
  list_port_forwards: {  };
  /** src/lib/ipc/tauri.ts invokeCheckHostKey; native/src/commands.rs */
  check_host_key: { request: { host: string; port: number; }; };
  /** src/lib/ipc/tauri.ts invokePreflightConnection; native/src/commands.rs */
  preflight_connection: { request: import("@/types/index").ConnectionPreflightRequest; };
  /** src/lib/ipc/tauri.ts invokeCancelConnectionPreflight; native/src/commands.rs */
  cancel_connection_preflight: { operationId: string; };
  /** src/lib/ipc/tauri.ts invokeTrustHost; native/src/commands.rs */
  trust_host: { request: { host: string; port: number; expectedFingerprint: string; }; };
  /** src/lib/ipc/tauri.ts invokeOpenUrl; native/src/commands.rs */
  open_url: { url: string; };
  /** src/lib/ipc/tauri.ts invokeListKnownHosts; native/src/commands.rs */
  list_known_hosts: {  };
  /** src/lib/ipc/tauri.ts invokeRemoveKnownHost; native/src/commands.rs */
  remove_known_host: { host: string; port: number; };
  /** src/lib/ipc/tauri.ts invokeListLogFiles; native/src/commands.rs */
  list_log_files: {  };
  /** src/lib/ipc/tauri.ts invokeReadLogFile; native/src/commands.rs */
  read_log_file: { name: string; };
  /** src/lib/ipc/tauri.ts invokeExportLogFile; native/src/commands.rs */
  export_log_file: { name: string; content: string; };
  /** src/lib/ipc/tauri.ts invokeListLocalDirectory; native/src/commands.rs */
  list_local_directory: { path: string; };
  /** src/lib/ipc/tauri.ts invokeListProfiles; native/src/commands.rs */
  list_profiles: {  };
  /** src/lib/ipc/tauri.ts invokeAddProfile; native/src/commands.rs */
  add_profile: { profile: import("@/types/index").ProfileRow; };
  /** src/lib/ipc/tauri.ts invokeUpdateProfile; native/src/commands.rs */
  update_profile: { id: string; profile: import("@/types/index").ProfileRow; };
  /** src/lib/ipc/tauri.ts invokeRemoveProfile; native/src/commands.rs */
  remove_profile: { id: string; };
  /** src/lib/ipc/tauri.ts invokeLoadPreferences; native/src/commands.rs */
  load_preferences: {  };
  /** src/lib/ipc/tauri.ts invokeSavePreferences; native/src/commands.rs */
  save_preferences: { entries: [string, string][]; };
  /** src/lib/ipc/tauri.ts invokeListRecentProfiles; native/src/commands.rs */
  list_recent_profiles: {  };
  /** src/lib/ipc/tauri.ts invokeTouchRecentProfile; native/src/commands.rs */
  touch_recent_profile: { profileId: string; };
  /** src/lib/ipc/tauri.ts invokeRemoveRecentProfile; native/src/commands.rs */
  remove_recent_profile: { profileId: string; };
  /** src/lib/ipc/tauri.ts invokeListSftpBookmarks; native/src/commands.rs */
  list_sftp_bookmarks: { host: string; port: number; username: string; };
  /** src/lib/ipc/tauri.ts invokeAddSftpBookmark; native/src/commands.rs */
  add_sftp_bookmark: { bookmark: import("@/types/index").SftpBookmarkRow; };
  /** src/lib/ipc/tauri.ts invokeRemoveSftpBookmark; native/src/commands.rs */
  remove_sftp_bookmark: { id: string; };
  /** src/lib/ipc/tauri.ts invokeLoadTerminalWorkspace; native/src/commands.rs */
  load_terminal_workspace: {  };
  /** src/lib/ipc/tauri.ts invokeSaveTerminalWorkspace; native/src/commands.rs */
  save_terminal_workspace: { sessionsJson: string; };
  /** src/lib/ipc/tauri.ts invokeClearTerminalWorkspace; native/src/commands.rs */
  clear_terminal_workspace: {  };
  /** src/lib/ipc/tauri.ts invokeLoadSftpWorkspace; native/src/commands.rs */
  load_sftp_workspace: {  };
  /** src/lib/ipc/tauri.ts invokeSaveSftpWorkspace; native/src/commands.rs */
  save_sftp_workspace: { workspaceJson: string; };
  /** src/lib/ipc/tauri.ts invokeClearSftpWorkspace; native/src/commands.rs */
  clear_sftp_workspace: {  };
  /** src/lib/ipc/tauri.ts invokeCollectRemoteHealthSnapshot; native/src/remote_health.rs */
  collect_remote_health_snapshot: { request: import("@/types/index").RemoteHealthSnapshotRequest; };
  /** src/lib/ipc/tauri.ts invokeCancelRemoteHealthSnapshot; native/src/remote_health.rs */
  cancel_remote_health_snapshot: { operationId: string; };
  /** src/lib/ipc/tauri.ts invokePrepareAgentImages; native/src/agent_runtime/commands.rs */
  agent_runtime_prepare_images: { images: readonly import("@/types/agent-image").AgentImageUpload[]; };
  /** src/lib/ipc/tauri.ts invokeSubmitAgentImages; native/src/agent_runtime/commands.rs */
  agent_runtime_submit_images: { input: { sessionId: string; clientOperationId: string; content: string; lane: "nextTurn" | "nextStep"; images: readonly import("@/types/agent-image").AgentImageUpload[]; }; };
  /** src/lib/ipc/tauri.ts invokeCancelAgentImageSubmission; native/src/agent_runtime/commands.rs */
  agent_runtime_cancel_image_submission: { input: { sessionId: string; clientOperationId: string; }; };
  /** src/lib/ipc/tauri.ts invokeAgentImagePreview; native/src/agent_runtime/commands.rs */
  agent_runtime_image_preview: { input: { sessionId: string; sha256: string; }; };
  /** src/lib/ipc/tauri.ts invokeCreateAgentRuntimeSession; native/src/agent_runtime/commands.rs */
  agent_runtime_create_session: { request: import("@/types/agent-session").CreateAgentSessionRequest; };
  /** src/lib/ipc/tauri.ts invokeSpawnAgentRuntimeSubagent; native/src/agent_runtime/commands.rs */
  agent_runtime_spawn_subagent: { request: import("@/types/agent-session").AgentSubagentSpawnRequest; };
  /** src/lib/ipc/tauri.ts invokeSendAgentRuntimeChildInput; native/src/agent_runtime/commands.rs */
  agent_runtime_send_child_input: { request: import("@/types/agent-session").AgentChildInputRequest; };
  /** src/lib/ipc/tauri.ts invokeInspectAgentRuntimeChild; native/src/agent_runtime/commands.rs */
  agent_runtime_inspect_child_agent: { request: import("@/types/agent-session").AgentChildRequest; };
  /** src/lib/ipc/tauri.ts invokeCancelAgentRuntimeChild; native/src/agent_runtime/commands.rs */
  agent_runtime_cancel_child_agent: { request: import("@/types/agent-session").AgentChildRequest; };
  /** src/lib/ipc/tauri.ts invokePlanAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_plan: { request: import("@/types/agent-session").AgentFleetPlanRequest; };
  /** src/lib/ipc/tauri.ts invokeStartAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_start: { request: import("@/types/agent-session").AgentFleetControlRequest; };
  /** src/lib/ipc/tauri.ts invokeResumeAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_resume: { request: import("@/types/agent-session").AgentFleetControlRequest; };
  /** src/lib/ipc/tauri.ts invokePauseAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_pause: { request: import("@/types/agent-session").AgentFleetControlRequest; };
  /** src/lib/ipc/tauri.ts invokeAbortAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_abort: { request: import("@/types/agent-session").AgentFleetControlRequest; };
  /** src/lib/ipc/tauri.ts invokeReconcileAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_reconcile: { request: import("@/types/agent-session").AgentFleetReconcileRequest; };
  /** src/lib/ipc/tauri.ts invokeStartAgentRuntime; native/src/agent_runtime/commands.rs */
  agent_runtime_start: { input: import("@/types/agent-session").AgentRuntimeStartInput; };
  /** src/lib/ipc/tauri.ts invokeSelectAgentRuntimeModel; native/src/agent_runtime/commands.rs */
  agent_runtime_select_model: { input: { sessionId: string; selection: import("@/types/ai").ModelSelection; }; };
  /** src/lib/ipc/tauri.ts invokeSetAgentRuntimePermission; native/src/agent_runtime/commands.rs */
  agent_runtime_set_permission: { input: { sessionId: string; mode: import("@/types/agent-session").AgentSessionPermissionMode; }; };
  /** src/lib/ipc/tauri.ts invokeAnswerAgentRuntimeQuestion; native/src/agent_runtime/commands.rs */
  agent_runtime_answer_question: { input: import("@/types/agent-question").AnswerQuestionInput; };
  /** src/lib/ipc/tauri.ts invokeAgentRuntimeFollowup; native/src/agent_runtime/commands.rs */
  agent_runtime_followup: { input: import("@/types/agent-session").AgentSessionMessageInput; };
  /** src/lib/ipc/tauri.ts invokeAgentRuntimeSteer; native/src/agent_runtime/commands.rs */
  agent_runtime_steer: { input: import("@/types/agent-session").AgentSessionMessageInput; };
  /** src/lib/ipc/tauri.ts invokeMutateAgentRuntimeInbox; native/src/agent_runtime/commands.rs */
  agent_runtime_mutate_inbox: { input: import("@/types/agent-session").AgentInboxMutationInput; };
  /** src/lib/ipc/tauri.ts invokeRenameAgentRuntimeSession; native/src/agent_runtime/commands.rs */
  agent_runtime_rename_session: { input: import("@/types/agent-session").AgentSessionRenameInput; };
  /** src/lib/ipc/tauri.ts invokeAgentRuntimeInject; native/src/agent_runtime/commands.rs */
  agent_runtime_inject: { input: import("@/types/agent-session").AgentRuntimeInjectionInput; };
  /** src/lib/ipc/tauri.ts invokeInterruptAgentRuntime; native/src/agent_runtime/commands.rs */
  agent_runtime_interrupt: { input: import("@/types/agent-session").AgentSessionIdInput; };
  /** src/lib/ipc/tauri.ts invokeResumeAgentRuntime; native/src/agent_runtime/commands.rs */
  agent_runtime_resume: { input: import("@/types/agent-session").AgentSessionIdInput; };
  /** src/lib/ipc/tauri.ts invokeCancelAgentRuntime; native/src/agent_runtime/commands.rs */
  agent_runtime_cancel: { input: import("@/types/agent-session").AgentSessionIdInput; };
  /** src/lib/ipc/tauri.ts invokeApproveAgentRuntimeTool; native/src/agent_runtime/commands.rs */
  agent_runtime_approve_tool: { input: import("@/types/agent-session").AgentRuntimeToolDecisionInput; };
  /** src/lib/ipc/tauri.ts invokeRejectAgentRuntimeTool; native/src/agent_runtime/commands.rs */
  agent_runtime_reject_tool: { input: import("@/types/agent-session").AgentRuntimeToolDecisionInput; };
  /** src/lib/ipc/tauri.ts invokeGetAgentRuntimeSession; native/src/agent_runtime/commands.rs */
  agent_runtime_get_session: { input: import("@/types/agent-session").AgentSessionIdInput; };
  /** src/lib/ipc/tauri.ts invokeListAgentRuntimeSessions; native/src/agent_runtime/commands.rs */
  agent_runtime_list_sessions: { request: import("@/types/agent-session").AgentSessionListRequest; };
  /** src/lib/ipc/tauri.ts invokeArchiveAgentRuntimeSession; native/src/agent_runtime/commands.rs */
  agent_runtime_archive_session: { input: import("@/types/agent-session").AgentSessionIdInput; };
  /** src/lib/ipc/tauri.ts invokeGetAgentRuntimeEvents; native/src/agent_runtime/commands.rs */
  agent_runtime_get_events: { request: import("@/types/agent-session").AgentSessionEventsRequest; };
  /** src/lib/ipc/tauri.ts invokeGetCommittedAgentRuntimeEvents; native/src/agent_runtime/commands.rs */
  agent_runtime_get_committed_events: { request: import("@/types/agent-session").AgentCommittedEventsRequest; };
  /** src/lib/ipc/tauri.ts invokeGetAgentRuntimeArtifact; native/src/agent_runtime/commands.rs */
  agent_runtime_get_artifact: { request: import("@/types/agent-session").AgentArtifactRequest; };
  /** src/lib/ipc/tauri.ts invokeInspectAgentRuntimeRecovery; native/src/agent_runtime/commands.rs */
  agent_runtime_inspect_recovery: { input: import("@/types/agent-session").AgentSessionIdInput; };
  /** src/lib/ipc/tauri.ts invokeResumeAgentRuntimeRecovery; native/src/agent_runtime/commands.rs */
  agent_runtime_resume_recovery: { input: import("@/types/agent-session").AgentSessionIdInput; };
  /** src/lib/ipc/tauri.ts invokeReconcileAgentRuntimeRecovery; native/src/agent_runtime/commands.rs */
  agent_runtime_reconcile_recovery: { input: import("@/types/agent-session").AgentRecoveryReconcileInput; };
  /** src/lib/ipc/tauri.ts invokeAbortAgentRuntimeRecovery; native/src/agent_runtime/commands.rs */
  agent_runtime_abort_recovery: { input: import("@/types/agent-session").AgentSessionIdInput; };
  /** src/lib/ipc/tauri.ts invokeListAgentRuntimeSkills; native/src/agent_runtime/commands.rs */
  agent_runtime_list_skills: { input: { sessionId: string; }; };
  /** src/lib/ipc/tauri.ts invokeListAgentFileReferences; native/src/agent_runtime/commands.rs */
  agent_runtime_list_file_references: { input: { sessionId: string; requestId: string; query: string; }; };
  /** src/lib/ipc/tauri.ts invokeListAgentFileReferences; native/src/agent_runtime/commands.rs */
  agent_runtime_cancel_file_references: { input: { sessionId: string; requestId: string; }; };
}
export interface CommandValues {
  /** src/lib/petdex/petdex.ts configurePetdex; native/src/petdex.rs */
  petdex_set_enabled: import("@/types").PetdexConnectionStatus;
  /** src/lib/petdex/petdex.ts getPetdexStatus; native/src/petdex.rs */
  petdex_get_status: import("@/types").PetdexConnectionStatus;
  /** src/lib/petdex/petdex.ts testPetdexConnection; native/src/petdex.rs */
  petdex_test_connection: import("@/types").PetdexConnectionStatus;
  /** src/lib/ipc/tauri.ts invokeGetSystemHealth; native/src/health.rs */
  get_system_health: import("@/types/index").SystemHealth;
  /** src/lib/ipc/tauri.ts invokeListAiRoutes; native/src/ai.rs */
  ai_list_routes: import("@/types/ai").RouteSnapshot;
  /** src/lib/ipc/tauri.ts invokeSaveAiRoutes; native/src/ai.rs */
  ai_save_routes: import("@/types/ai").RouteSnapshot;
  /** src/lib/ipc/tauri.ts invokeListAiRouteModels; native/src/ai.rs */
  ai_list_route_models: { revision: number; models: import("@/lib/ai/provider-contract").ResolvedModel[]; };
  /** src/lib/ipc/tauri.ts invokeResolveAiSelection; native/src/ai.rs */
  ai_resolve_selection: import("@/lib/ai/provider-contract").ResolvedModel;
  /** src/lib/ipc/tauri.ts invokeListAiSessionMigrations; native/src/ai.rs */
  ai_list_session_migrations: { sessionId: string; status: "pending" | "converted" | "failed"; }[];
  /** src/lib/ipc/tauri.ts invokeConvertAiSessionV4; native/src/ai.rs */
  ai_convert_session_v4_to_v5: { source: string; destination: string; events: number; status: string; };
  /** src/lib/ipc/tauri.ts invokeListAiModels; native/src/ai.rs */
  ai_list_models: string[];
  /** src/lib/ai/provider-contract.ts loadResolvedModel; native/src/ai.rs */
  ai_resolve_model: import("@/lib/ai/provider-contract").ResolvedModel;
  /** src/components/ai/provider-setup-dialog.tsx ; native/src/ai.rs */
  ai_model_declaration_template: import("@/lib/ai/provider-contract").ModelDefinition;
  /** src/lib/ipc/tauri.ts invokeCreateSession; native/src/commands.rs */
  create_session: import("@/types/index").SessionSummary;
  /** src/lib/ipc/tauri.ts invokeCreateLocalSession; native/src/commands.rs */
  create_local_session: import("@/types/index").SessionSummary;
  /** src/lib/ipc/tauri.ts invokeWriteSession; native/src/commands.rs */
  write_session: void;
  /** src/lib/ipc/tauri.ts invokeGetSessionStatus; native/src/commands.rs */
  get_session_status: import("@/types/index").StatusEvent;
  /** src/lib/ipc/tauri.ts invokeMarkSessionReady; native/src/commands.rs */
  mark_session_ready: void;
  /** src/lib/ipc/tauri.ts invokeSetSessionOutputPaused; native/src/commands.rs */
  set_session_output_paused: void;
  /** src/lib/ipc/tauri.ts invokeResizeSession; native/src/commands.rs */
  resize_session: void;
  /** src/lib/ipc/tauri.ts invokeCloseSession; native/src/commands.rs */
  close_session: void;
  /** src/lib/ipc/tauri.ts invokeRequestAppRestart; native/src/commands.rs */
  request_app_restart: void;
  /** src/App.tsx ; native/src/commands.rs */
  request_app_exit: void;
  /** src/lib/ipc/tauri.ts invokeListRemoteDirectory; native/src/commands.rs */
  list_remote_directory: import("@/types/index").RemoteDirectoryListing;
  /** src/lib/ipc/tauri.ts invokeSupersedeRemoteDirectoryRequest; native/src/commands.rs */
  supersede_remote_directory_request: void;
  /** src/lib/ipc/tauri.ts invokeResolveRemoteEntryOwners; native/src/commands.rs */
  resolve_remote_entry_owners: import("@/types/index").RemoteEntryOwners;
  /** src/lib/ipc/tauri.ts invokeWarmRemoteConnection; native/src/commands.rs */
  warm_remote_connection: void;
  /** src/lib/ipc/tauri.ts invokeCreateRemoteEntry; native/src/commands.rs */
  create_remote_entry: void;
  /** src/lib/ipc/tauri.ts invokeRenameRemotePath; native/src/commands.rs */
  rename_remote_path: void;
  /** src/lib/ipc/tauri.ts invokeDeleteRemotePath; native/src/commands.rs */
  delete_remote_path: void;
  /** src/lib/ipc/tauri.ts invokeCopyRemotePath; native/src/commands.rs */
  copy_remote_path: void;
  /** src/lib/ipc/tauri.ts invokeCopyRemoteToRemote; native/src/commands.rs */
  copy_remote_to_remote: void;
  /** src/lib/ipc/tauri.ts invokeCancelRemoteCopy; native/src/commands.rs */
  cancel_remote_copy: void;
  /** src/lib/ipc/tauri.ts invokeUploadLocalPaths; native/src/commands.rs */
  upload_local_paths: import("@/types/index").TransferBatchResult;
  /** src/lib/ipc/tauri.ts invokeCopyLocalPaths; native/src/commands.rs */
  copy_local_paths: void;
  /** src/lib/ipc/tauri.ts invokeRenameLocalPath; native/src/commands.rs */
  rename_local_path: void;
  /** src/lib/ipc/tauri.ts invokePasteLocalPaths; native/src/commands.rs */
  paste_local_paths: string[];
  /** src/lib/ipc/tauri.ts invokeTrashLocalPaths; native/src/commands.rs */
  trash_local_paths: void;
  /** src/lib/ipc/tauri.ts invokeCancelUpload; native/src/commands.rs */
  cancel_upload: void;
  /** src/lib/ipc/tauri.ts invokeCancelDelete; native/src/commands.rs */
  cancel_delete: void;
  /** src/lib/ipc/tauri.ts invokeDownloadRemotePaths; native/src/commands.rs */
  download_remote_paths: import("@/types/index").TransferBatchResult;
  /** src/lib/ipc/tauri.ts invokeCancelDownload; native/src/commands.rs */
  cancel_download: void;
  /** src/lib/ipc/tauri.ts invokeDisconnectSftp; native/src/commands.rs */
  disconnect_sftp: void;
  /** src/lib/ipc/tauri.ts invokeOpenPath; native/src/commands.rs */
  open_path: void;
  /** src/lib/ipc/tauri.ts invokePickLocalFiles; native/src/commands.rs */
  pick_local_files: string[];
  /** src/lib/ipc/tauri.ts invokePickLocalFolder; native/src/commands.rs */
  pick_local_folder: string[];
  /** src/lib/ipc/tauri.ts invokePickPrivateKeyFile; native/src/commands.rs */
  pick_private_key_file: string | null;
  /** src/lib/ipc/tauri.ts invokeOpenRemoteFile; native/src/commands.rs */
  open_remote_file: void;
  /** src/lib/ipc/tauri.ts invokePreviewLocalFile; native/src/commands.rs */
  preview_local_file: import("@/types/index").ReadRemoteFileResponse;
  /** src/lib/ipc/tauri.ts invokePreviewRemoteFile; native/src/commands.rs */
  preview_remote_file: import("@/types/index").ReadRemoteFileResponse;
  /** src/lib/ipc/tauri.ts invokeCancelRemoteFileRead; native/src/commands.rs */
  cancel_remote_file_read: void;
  /** src/lib/ipc/tauri.ts invokeUpdateRemotePermissions; native/src/commands.rs */
  update_remote_permissions: void;
  /** src/lib/ipc/tauri.ts invokeStoreKeyCredential; native/src/commands.rs */
  store_key_credential: void;
  /** src/lib/ipc/tauri.ts invokeListKeyCredentials; native/src/commands.rs */
  list_key_credentials: import("@/lib/desktop/wire-types").KeyCredentialSummary[];
  /** src/lib/ipc/tauri.ts invokeRetrieveKeyCredential; native/src/commands.rs */
  retrieve_key_credential: import("@/lib/desktop/wire-types").KeyCredentialResponse | null;
  /** src/lib/ipc/tauri.ts invokeDeleteKeyCredential; native/src/commands.rs */
  delete_key_credential: string[];
  /** src/lib/ipc/tauri.ts invokeReadTextFile; native/src/commands.rs */
  read_text_file: string;
  /** src/lib/ipc/tauri.ts invokeStoreProfilePassword; native/src/commands.rs */
  store_profile_password: void;
  /** src/lib/ipc/tauri.ts invokeRetrieveProfilePassword; native/src/commands.rs */
  retrieve_profile_password: string | null;
  /** src/lib/ipc/tauri.ts invokeDeleteProfilePassword; native/src/commands.rs */
  delete_profile_password: void;
  /** src/lib/ipc/tauri.ts invokeStoreProfileSecret; native/src/commands.rs */
  store_profile_secret: void;
  /** src/lib/ipc/tauri.ts invokeRetrieveProfileSecret; native/src/commands.rs */
  retrieve_profile_secret: string | null;
  /** src/lib/ipc/tauri.ts invokeDeleteProfileSecrets; native/src/commands.rs */
  delete_profile_secrets: void;
  /** src/lib/ipc/tauri.ts invokeDeleteProfileSecret; native/src/commands.rs */
  delete_profile_secret: void;
  /** src/lib/ipc/tauri.ts invokeStartPortForward; native/src/commands.rs */
  start_port_forward: import("@/types/index").PortForwardRuntime;
  /** src/lib/ipc/tauri.ts invokeStopPortForward; native/src/commands.rs */
  stop_port_forward: import("@/types/index").PortForwardRuntime;
  /** src/lib/ipc/tauri.ts invokeStopAllPortForwards; native/src/commands.rs */
  stop_all_port_forwards: import("@/types/index").PortForwardRuntime[];
  /** src/lib/ipc/tauri.ts invokeListPortForwards; native/src/commands.rs */
  list_port_forwards: import("@/types/index").PortForwardRuntime[];
  /** src/lib/ipc/tauri.ts invokeCheckHostKey; native/src/commands.rs */
  check_host_key: import("@/types/index").HostKeyCheckResult;
  /** src/lib/ipc/tauri.ts invokePreflightConnection; native/src/commands.rs */
  preflight_connection: import("@/types/index").ConnectionPreflightResult;
  /** src/lib/ipc/tauri.ts invokeCancelConnectionPreflight; native/src/commands.rs */
  cancel_connection_preflight: void;
  /** src/lib/ipc/tauri.ts invokeTrustHost; native/src/commands.rs */
  trust_host: void;
  /** src/lib/ipc/tauri.ts invokeOpenUrl; native/src/commands.rs */
  open_url: void;
  /** src/lib/ipc/tauri.ts invokeListKnownHosts; native/src/commands.rs */
  list_known_hosts: import("@/types/index").KnownHostEntry[];
  /** src/lib/ipc/tauri.ts invokeRemoveKnownHost; native/src/commands.rs */
  remove_known_host: void;
  /** src/lib/ipc/tauri.ts invokeListLogFiles; native/src/commands.rs */
  list_log_files: import("@/types/index").LogFileInfo[];
  /** src/lib/ipc/tauri.ts invokeReadLogFile; native/src/commands.rs */
  read_log_file: string;
  /** src/lib/ipc/tauri.ts invokeExportLogFile; native/src/commands.rs */
  export_log_file: string | null;
  /** src/lib/ipc/tauri.ts invokeListLocalDirectory; native/src/commands.rs */
  list_local_directory: import("@/types/index").LocalDirectoryListing;
  /** src/lib/ipc/tauri.ts invokeListProfiles; native/src/commands.rs */
  list_profiles: import("@/types/index").ProfileRow[];
  /** src/lib/ipc/tauri.ts invokeAddProfile; native/src/commands.rs */
  add_profile: void;
  /** src/lib/ipc/tauri.ts invokeUpdateProfile; native/src/commands.rs */
  update_profile: void;
  /** src/lib/ipc/tauri.ts invokeRemoveProfile; native/src/commands.rs */
  remove_profile: void;
  /** src/lib/ipc/tauri.ts invokeLoadPreferences; native/src/commands.rs */
  load_preferences: [string, string][];
  /** src/lib/ipc/tauri.ts invokeSavePreferences; native/src/commands.rs */
  save_preferences: void;
  /** src/lib/ipc/tauri.ts invokeListRecentProfiles; native/src/commands.rs */
  list_recent_profiles: string[];
  /** src/lib/ipc/tauri.ts invokeTouchRecentProfile; native/src/commands.rs */
  touch_recent_profile: void;
  /** src/lib/ipc/tauri.ts invokeRemoveRecentProfile; native/src/commands.rs */
  remove_recent_profile: void;
  /** src/lib/ipc/tauri.ts invokeListSftpBookmarks; native/src/commands.rs */
  list_sftp_bookmarks: import("@/types/index").SftpBookmarkRow[];
  /** src/lib/ipc/tauri.ts invokeAddSftpBookmark; native/src/commands.rs */
  add_sftp_bookmark: void;
  /** src/lib/ipc/tauri.ts invokeRemoveSftpBookmark; native/src/commands.rs */
  remove_sftp_bookmark: void;
  /** src/lib/ipc/tauri.ts invokeLoadTerminalWorkspace; native/src/commands.rs */
  load_terminal_workspace: string | null;
  /** src/lib/ipc/tauri.ts invokeSaveTerminalWorkspace; native/src/commands.rs */
  save_terminal_workspace: void;
  /** src/lib/ipc/tauri.ts invokeClearTerminalWorkspace; native/src/commands.rs */
  clear_terminal_workspace: void;
  /** src/lib/ipc/tauri.ts invokeLoadSftpWorkspace; native/src/commands.rs */
  load_sftp_workspace: string | null;
  /** src/lib/ipc/tauri.ts invokeSaveSftpWorkspace; native/src/commands.rs */
  save_sftp_workspace: void;
  /** src/lib/ipc/tauri.ts invokeClearSftpWorkspace; native/src/commands.rs */
  clear_sftp_workspace: void;
  /** src/lib/ipc/tauri.ts invokeCollectRemoteHealthSnapshot; native/src/remote_health.rs */
  collect_remote_health_snapshot: import("@/types/index").RemoteHealthSnapshotResult;
  /** src/lib/ipc/tauri.ts invokeCancelRemoteHealthSnapshot; native/src/remote_health.rs */
  cancel_remote_health_snapshot: void;
  /** src/lib/ipc/tauri.ts invokePrepareAgentImages; native/src/agent_runtime/commands.rs */
  agent_runtime_prepare_images: import("@/types/agent-image").AgentImageUpload[];
  /** src/lib/ipc/tauri.ts invokeSubmitAgentImages; native/src/agent_runtime/commands.rs */
  agent_runtime_submit_images: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeCancelAgentImageSubmission; native/src/agent_runtime/commands.rs */
  agent_runtime_cancel_image_submission: boolean;
  /** src/lib/ipc/tauri.ts invokeAgentImagePreview; native/src/agent_runtime/commands.rs */
  agent_runtime_image_preview: string;
  /** src/lib/ipc/tauri.ts invokeCreateAgentRuntimeSession; native/src/agent_runtime/commands.rs */
  agent_runtime_create_session: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeSpawnAgentRuntimeSubagent; native/src/agent_runtime/commands.rs */
  agent_runtime_spawn_subagent: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeSendAgentRuntimeChildInput; native/src/agent_runtime/commands.rs */
  agent_runtime_send_child_input: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeInspectAgentRuntimeChild; native/src/agent_runtime/commands.rs */
  agent_runtime_inspect_child_agent: import("@/types/agent-session").AgentChildInspection;
  /** src/lib/ipc/tauri.ts invokeCancelAgentRuntimeChild; native/src/agent_runtime/commands.rs */
  agent_runtime_cancel_child_agent: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokePlanAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_plan: import("@/types/agent-session").AgentFleetInspection;
  /** src/lib/ipc/tauri.ts invokeStartAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_start: import("@/types/agent-session").AgentFleetInspection;
  /** src/lib/ipc/tauri.ts invokeResumeAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_resume: import("@/types/agent-session").AgentFleetInspection;
  /** src/lib/ipc/tauri.ts invokePauseAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_pause: import("@/types/agent-session").AgentFleetInspection;
  /** src/lib/ipc/tauri.ts invokeAbortAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_abort: import("@/types/agent-session").AgentFleetInspection;
  /** src/lib/ipc/tauri.ts invokeReconcileAgentRuntimeFleet; native/src/agent_runtime/commands.rs */
  agent_runtime_fleet_reconcile: import("@/types/agent-session").AgentFleetInspection;
  /** src/lib/ipc/tauri.ts invokeStartAgentRuntime; native/src/agent_runtime/commands.rs */
  agent_runtime_start: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeSelectAgentRuntimeModel; native/src/agent_runtime/commands.rs */
  agent_runtime_select_model: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeSetAgentRuntimePermission; native/src/agent_runtime/commands.rs */
  agent_runtime_set_permission: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeAnswerAgentRuntimeQuestion; native/src/agent_runtime/commands.rs */
  agent_runtime_answer_question: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeAgentRuntimeFollowup; native/src/agent_runtime/commands.rs */
  agent_runtime_followup: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeAgentRuntimeSteer; native/src/agent_runtime/commands.rs */
  agent_runtime_steer: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeMutateAgentRuntimeInbox; native/src/agent_runtime/commands.rs */
  agent_runtime_mutate_inbox: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeRenameAgentRuntimeSession; native/src/agent_runtime/commands.rs */
  agent_runtime_rename_session: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeAgentRuntimeInject; native/src/agent_runtime/commands.rs */
  agent_runtime_inject: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeInterruptAgentRuntime; native/src/agent_runtime/commands.rs */
  agent_runtime_interrupt: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeResumeAgentRuntime; native/src/agent_runtime/commands.rs */
  agent_runtime_resume: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeCancelAgentRuntime; native/src/agent_runtime/commands.rs */
  agent_runtime_cancel: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeApproveAgentRuntimeTool; native/src/agent_runtime/commands.rs */
  agent_runtime_approve_tool: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeRejectAgentRuntimeTool; native/src/agent_runtime/commands.rs */
  agent_runtime_reject_tool: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeGetAgentRuntimeSession; native/src/agent_runtime/commands.rs */
  agent_runtime_get_session: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeListAgentRuntimeSessions; native/src/agent_runtime/commands.rs */
  agent_runtime_list_sessions: import("@/types/agent-session").AgentSessionListPage;
  /** src/lib/ipc/tauri.ts invokeArchiveAgentRuntimeSession; native/src/agent_runtime/commands.rs */
  agent_runtime_archive_session: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeGetAgentRuntimeEvents; native/src/agent_runtime/commands.rs */
  agent_runtime_get_events: import("@/types/agent-session").AgentSessionEventPage;
  /** src/lib/ipc/tauri.ts invokeGetCommittedAgentRuntimeEvents; native/src/agent_runtime/commands.rs */
  agent_runtime_get_committed_events: import("@/types/agent-session").AgentSessionEventPage;
  /** src/lib/ipc/tauri.ts invokeGetAgentRuntimeArtifact; native/src/agent_runtime/commands.rs */
  agent_runtime_get_artifact: import("@/types/agent-session").AgentArtifactResponse;
  /** src/lib/ipc/tauri.ts invokeInspectAgentRuntimeRecovery; native/src/agent_runtime/commands.rs */
  agent_runtime_inspect_recovery: import("@/types/agent-session").AgentRecoveryCheckpoint;
  /** src/lib/ipc/tauri.ts invokeResumeAgentRuntimeRecovery; native/src/agent_runtime/commands.rs */
  agent_runtime_resume_recovery: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeReconcileAgentRuntimeRecovery; native/src/agent_runtime/commands.rs */
  agent_runtime_reconcile_recovery: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeAbortAgentRuntimeRecovery; native/src/agent_runtime/commands.rs */
  agent_runtime_abort_recovery: import("@/types/agent-session").AgentSessionSnapshot;
  /** src/lib/ipc/tauri.ts invokeListAgentRuntimeSkills; native/src/agent_runtime/commands.rs */
  agent_runtime_list_skills: import("@/types/agent-skill").SkillUserList;
  /** src/lib/ipc/tauri.ts invokeListAgentFileReferences; native/src/agent_runtime/commands.rs */
  agent_runtime_list_file_references: import("@/types/agent-file-reference").FileReferenceList;
  /** src/lib/ipc/tauri.ts invokeListAgentFileReferences; native/src/agent_runtime/commands.rs */
  agent_runtime_cancel_file_references: void;
}
export type CommandInput<C extends keyof CommandArgs> = {} extends CommandArgs[C] ? [args?: CommandArgs[C]] : [args: CommandArgs[C]];
export type WireValue<T> = [T] extends [void] ? null : T;
