//! Compatibility with the fixed baseline's Tauri 2.11.5 JSON CommandArg.
//! Keep missing Option distinct from a missing required argument and deserialize
//! borrowed Values, as the baseline does (not a second JavaScript schema).
use serde::{
    de::{DeserializeOwned, Error, Visitor},
    Deserializer,
};
use serde_json::{json, Value};
struct Argument<'a> {
    args: &'a Value,
    key: &'a str,
    command: &'a str,
}
impl<'a> Argument<'a> {
    fn value(&self) -> serde_json::Result<&'a Value> {
        self.args.get(self.key).ok_or_else(|| {
            serde_json::Error::custom(format!(
                "command {} missing required key {}",
                self.command, self.key
            ))
        })
    }
}
macro_rules! delegate {
    ($method:ident $(, $arg:ident: $typ:ty)*) => {
        fn $method<V: Visitor<'de>>(self, $($arg: $typ,)* visitor: V) -> Result<V::Value, Self::Error> {
            self.value()?.$method($($arg,)* visitor)
        }
    };
}
impl<'de> Deserializer<'de> for Argument<'de> {
    type Error = serde_json::Error;
    delegate!(deserialize_any);
    delegate!(deserialize_bool);
    delegate!(deserialize_i8);
    delegate!(deserialize_i16);
    delegate!(deserialize_i32);
    delegate!(deserialize_i64);
    delegate!(deserialize_u8);
    delegate!(deserialize_u16);
    delegate!(deserialize_u32);
    delegate!(deserialize_u64);
    delegate!(deserialize_f32);
    delegate!(deserialize_f64);
    delegate!(deserialize_char);
    delegate!(deserialize_str);
    delegate!(deserialize_string);
    delegate!(deserialize_bytes);
    delegate!(deserialize_byte_buf);
    delegate!(deserialize_unit);
    delegate!(deserialize_unit_struct, name: &'static str);
    delegate!(deserialize_newtype_struct, name: &'static str);
    delegate!(deserialize_seq);
    delegate!(deserialize_tuple, len: usize);
    delegate!(deserialize_tuple_struct, name: &'static str, len: usize);
    delegate!(deserialize_map);
    delegate!(deserialize_struct, name: &'static str, fields: &'static [&'static str]);
    delegate!(deserialize_enum, name: &'static str, variants: &'static [&'static str]);
    delegate!(deserialize_identifier);
    delegate!(deserialize_ignored_any);
    fn deserialize_option<V: Visitor<'de>>(self, visitor: V) -> Result<V::Value, Self::Error> {
        match self.args.get(self.key) {
            Some(value) => value.deserialize_option(visitor),
            None => visitor.visit_none(),
        }
    }
}
pub(crate) fn argument<T: DeserializeOwned>(
    args: &Value,
    key: &str,
    command: &str,
) -> Result<T, Value> {
    T::deserialize(Argument { args, key, command })
        .map_err(|e| json!(format!("invalid args `{key}` for command `{command}`: {e}")))
}

/// Private protocol validation; these commands still execute dialogs in Electron.
/// No new renderer command or business operation is registered.
pub(crate) fn validate_desktop(command: &str, args: &Value) -> Result<Value, Value> {
    match command {
        "pick_local_files" | "pick_private_key_file" => {}
        "pick_local_folder" => {
            let _: Option<String> = argument(args, "title", command)?;
        }
        "export_log_file" => {
            let _: String = argument(args, "name", command)?;
            let _: String = argument(args, "content", command)?;
        }
        _ => return Err(json!("unknown desktop validation command")),
    }
    Ok(Value::Null)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde::Serialize;
    #[derive(serde::Deserialize, Serialize)]
    #[serde(rename_all = "camelCase", deny_unknown_fields)]
    struct Nested {
        port: u16,
        title: Option<String>,
    }
    fn decode<T: DeserializeOwned + Serialize>(args: &Value, command: &str) -> Value {
        serde_json::to_value(
            argument::<T>(args, "value", command).map(|v| serde_json::to_value(v).unwrap()),
        )
        .unwrap()
    }
    #[test]
    fn fixed_tauri_missing_null_nested_and_range_results_match() {
        // Generated by the independent actual Tauri 2.11.5 mock-runtime probe.
        let cases: Vec<Value> =
            serde_json::from_str(include_str!("../tests/fixtures/tauri-argument-cases.json"))
                .unwrap();
        assert_eq!(cases.len(), 24);
        for case in cases {
            let cmd = case["command"].as_str().unwrap();
            let args = &case["args"];
            let actual = match cmd {
                "string_arg" => decode::<String>(args, cmd),
                "optional_arg" => decode::<Option<String>>(args, cmd),
                "integer_arg" => decode::<u16>(args, cmd),
                "tuple_arg" => decode::<Vec<(String, String)>>(args, cmd),
                "nested_arg" => decode::<Nested>(args, cmd),
                _ => panic!("unexpected fixture command"),
            };
            assert_eq!(actual, case["baseline"], "{cmd}: {args}");
        }
    }
}
